### ISSUE TITLE
Alarms disabled - error decoding string

### ISSUE THREAD

**Issue by Awesomeragle** [vicolo-dev/chrono#384]
**Describe the bug**

No alarms are ringing anymore. I have the following error code.

Error decoding string: FormatException: Unexpected character (at character 19952) ....Alarm(0: Updating all alarms on trigger""isActive" false} Active": false})

First day of download half the alarms worked and then they stopped but I'm not sure exactly what time they stopped.

**To Reproduce**
No steps known for reproduction. The error is persistent and I cannot get it to start sounding alarms again. Below is my setup.

14 hourly alarms from 9am - 10pm. 
Most are every day, some are set to specific week days.
Other than the time/day all alarms are identical. 10 character basic label, bright melody, volume 0%, vibration on, snooze 5 minutes, 0 tasks. Anything not mentioned is default value.

**Expected behavior**

Alarms to go off and the error code not be displayed.

**Screenshots**

**Smartphone Information**
 - Device: Google Pixel 6
 - OS: Android 14
 - App version: 0.6.0-beta1

**Additional context**

**Comment by rom1v** [comment]
Same problem.

In `adb logcat`:
```
11-22 14:54:09.840 14401  9795 I flutter : ┌───────────────────────────────────────────────────────────────────────────────
11-22 14:54:09.840 14401  9795 I flutter : │ #0   listFromString (package:clock_app/common/utils/json_serialize.dart:55)
11-22 14:54:09.840 14401  9795 I flutter : │ #1   loadList (package:clock_app/common/utils/list_storage.dart:59)
11-22 14:54:09.840 14401  9795 I flutter : │ #2   <asynchronous suspension>
11-22 14:54:09.840 14401  9795 I flutter : │ #3   scheduleAlarm (package:clock_app/alarm/logic/schedule_alarm.dart:30)
11-22 14:54:09.840 14401  9795 I flutter : │ #4   <asynchronous suspension>
11-22 14:54:09.840 14401  9795 I flutter : │ #5   AlarmRunner.schedule (package:clock_app/alarm/types/alarm_runner.dart:20)
11-22 14:54:09.840 14401  9795 I flutter : │ #6   <asynchronous suspension>
11-22 14:54:09.840 14401  9795 I flutter : │ #7   OnceAlarmSchedule.schedule (package:clock_app/alarm/types/schedules/once_alarm_schedule.dart:34)
11-22 14:54:09.840 14401  9795 I flutter : │ #8   <asynchronous suspension>
11-22 14:54:09.840 14401  9795 I flutter : │ #9   Alarm.schedule (package:clock_app/alarm/types/alarm.dart:258)
11-22 14:54:09.840 14401  9795 I flutter : │ #10   <asynchronous suspension>
11-22 14:54:09.840 14401  9795 I flutter : │ #11   Alarm.enable (package:clock_app/alarm/types/alarm.dart:295)
11-22 14:54:09.840 14401  9795 I flutter : │ #12   <asynchronous suspension>
11-22 14:54:09.840 14401  9795 I flutter : │ #13   Alarm.setIsEnabled (package:clock_app/alarm/types/alarm.dart:212)
11-22 14:54:09.840 14401  9795 I flutter : │ #14   <asynchronous suspension>
11-22 14:54:09.840 14401  9795 I flutter : │ #15   _AlarmScreenState._handleEnableChangeAlarm (package:clock_app/alarm/screens/alarm_screen.dart:146)
11-22 14:54:09.840 14401  9795 I flutter : │ #16   <asynchronous suspension>
11-22 14:54:09.840 14401  9795 I flutter : ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
11-22 14:54:09.840 14401  9795 I flutter : │ ⛔ Error decoding string: FormatException: Unexpected character (at character 19837)
11-22 14:54:09.840 14401  9795 I flutter : │ ⛔ ...rvice] Update alarms in background service","isActive":false}]tive":false}]
11-22 14:54:09.840 14401  9795 I flutter : │ ⛔                                                                  ^
11-22 14:54:09.840 14401  9795 I flutter : │ ⛔ 
11-22 14:54:09.840 14401  9795 I flutter : └───────────────────────────────────────────────────────────────────────────────
```

![clock](https://github.com/user-attachments/assets/6b45558b-c783-4236-bb52-09dd468ccacb)

**Comment by UcraNerd** [comment]
![Screenshot_2024-12-07-09-47-06-916_com.vicolo.chrono.jpg](https://github.com/user-attachments/assets/4be00981-67d8-47ec-8b08-5d7bac685764)

Same error

**Comment by Michmcb** [comment]
Also getting the same issue.
![Uploading Screenshot_20241224-183741.png…]()

**Comment by AhsanSarwar45** [comment]
Try beta-2.

**Comment by AhsanSarwar45** [comment]
Should be fixed in the 0.6.0. Feel free to reopen if you face the issue again.
